export const propertyData = [
  {
    id: 1,
    title: 'Vila Modern di Tepi Pantai',
    description:
      'Vila mewah dengan pemandangan laut yang menakjubkan, kolam renang pribadi, dan akses langsung ke pantai.',
    ratings: 4.9,
    sales: 120,
    views: 15000,
    topQuality: true,
    isActive: true,
    pricing: 7500000000,
    image: 'src/assets/images/property-1.jpg',
    location: 'Bali, Indonesia',
    type: 'Vila',
    bedrooms: 5,
    bathrooms: 5,
    area: 600,
  },
  {
    id: 2,
    title: 'Apartemen Pusat Kota',
    description:
      'Apartemen modern di jantung kota dengan akses mudah ke pusat perbelanjaan dan transportasi umum.',
    ratings: 4.7,
    sales: 250,
    views: 22000,
    topQuality: false,
    isActive: true,
    pricing: 2500000000,
    image: 'src/assets/images/property-2.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 1,
    area: 75,
  },
  {
    id: 3,
    title: 'Rumah Klasik di Pedesaan',
    description:
      'Rumah bergaya klasik dengan taman yang luas, cocok untuk keluarga yang mencari ketenangan.',
    ratings: 4.8,
    sales: 95,
    views: 18000,
    topQuality: true,
    isActive: true,
    pricing: 4200000000,
    image: 'src/assets/images/property-3.jpg',
    location: 'Bandung, Indonesia',
    type: 'Rumah',
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
  },
  {
    id: 4,
    title: 'Penthouse Mewah dengan Pemandangan Kota',
    description:
      'Penthouse eksklusif di lantai atas dengan pemandangan 360 derajat kota metropolitan.',
    ratings: 4.9,
    sales: 60,
    views: 25000,
    topQuality: true,
    isActive: true,
    pricing: 15000000000,
    image: 'src/assets/images/property-4.jpg',
    location: 'Surabaya, Indonesia',
    type: 'Penthouse',
    bedrooms: 3,
    bathrooms: 4,
    area: 400,
  },
  {
    id: 5,
    title: 'Rumah Minimalis di Kompleks Elit',
    description:
      'Rumah desain minimalis modern di dalam kompleks perumahan yang aman dan nyaman.',
    ratings: 4.6,
    sales: 180,
    views: 19500,
    topQuality: false,
    isActive: true,
    pricing: 3100000000,
    image: 'src/assets/images/property-5.jpg',
    location: 'Tangerang, Indonesia',
    type: 'Rumah',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
  },
  {
    id: 6,
    title: 'Loft Industrial di Pusat Kreatif',
    description:
      'Loft dengan desain industrial yang unik, terletak di area kreatif dan dekat dengan galeri seni.',
    ratings: 4.7,
    sales: 110,
    views: 16000,
    topQuality: false,
    isActive: true,
    pricing: 1800000000,
    image: 'src/assets/images/property-6.jpg',
    location: 'Yogyakarta, Indonesia',
    type: 'Loft',
    bedrooms: 1,
    bathrooms: 1,
    area: 120,
  },
  {
    id: 7,
    title: 'Resor Tepi Danau',
    description:
      'Properti resor yang tenang di tepi danau, menawarkan pemandangan danau dan pegunungan.',
    ratings: 4.8,
    sales: 80,
    views: 21000,
    topQuality: true,
    isActive: true,
    pricing: 6800000000,
    image: 'src/assets/images/property-7.jpg',
    location: 'Toba, Indonesia',
    type: 'Resor',
    bedrooms: 10,
    bathrooms: 12,
    area: 1200,
  },
  {
    id: 8,
    title: 'Townhouse Modern Keluarga',
    description:
      'Townhouse nyaman dengan fasilitas lengkap untuk keluarga, termasuk taman bermain anak.',
    ratings: 4.6,
    sales: 210,
    views: 20500,
    topQuality: false,
    isActive: true,
    pricing: 2200000000,
    image: 'src/assets/images/property-8.jpg',
    location: 'Bekasi, Indonesia',
    type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 3,
    area: 150,
  },
  {
    id: 9,
    title: 'Bungalow Tropis Tersembunyi',
    description:
      'Bungalow pribadi yang dikelilingi oleh taman tropis yang rimbun, surga tersembunyi Anda.',
    ratings: 4.9,
    sales: 90,
    views: 17000,
    topQuality: true,
    isActive: true,
    pricing: 3500000000,
    image: 'src/assets/images/property-9.jpg',
    location: 'Lombok, Indonesia',
    type: 'Bungalow',
    bedrooms: 2,
    bathrooms: 2,
    area: 250,
  },
  {
    id: 10,
    title: 'Apartemen Studio Compact',
    description:
      'Apartemen studio yang efisien dan fungsional, ideal untuk para profesional muda atau mahasiswa.',
    ratings: 4.5,
    sales: 300,
    views: 23000,
    topQuality: false,
    isActive: false,
    pricing: 950000000,
    image: 'src/assets/images/property-10.jpg',
    location: 'Depok, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 35,
  },
  {
    id: 11,
    title: 'Rumah Perbukitan dengan Pemandangan Indah',
    description:
      'Rumah di perbukitan yang menawarkan pemandangan lembah dan udara yang sejuk dan segar.',
    ratings: 4.8,
    sales: 105,
    views: 19000,
    topQuality: true,
    isActive: true,
    pricing: 5200000000,
    image: 'src/assets/images/property-11.jpg',
    location: 'Bogor, Indonesia',
    type: 'Rumah',
    bedrooms: 4,
    bathrooms: 4,
    area: 450,
  },
  {
    id: 12,
    title: 'Kondominium Mewah Tepi Laut',
    description:
      'Kondominium dengan fasilitas bintang lima dan pemandangan langsung ke samudra.',
    ratings: 4.9,
    sales: 75,
    views: 24000,
    topQuality: true,
    isActive: true,
    pricing: 12000000000,
    image: 'src/assets/images/property-12.jpg',
    location: 'Manado, Indonesia',
    type: 'Kondominium',
    bedrooms: 3,
    bathrooms: 3,
    area: 300,
  },
  {
    id: 13,
    title: 'Rumah Kontemporer di Lingkungan Hijau',
    description:
      'Rumah modern dengan banyak bukaan kaca, menyatu dengan lingkungan hijau di sekitarnya.',
    ratings: 4.7,
    sales: 130,
    views: 18500,
    topQuality: false,
    isActive: true,
    pricing: 3800000000,
    image: 'src/assets/images/property-13.jpg',
    location: 'Semarang, Indonesia',
    type: 'Rumah',
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
  },
  {
    id: 14,
    title: 'Apartemen Dupleks Stylish',
    description:
      'Apartemen dua lantai dengan desain interior yang stylish dan pemanfaatan ruang yang cerdas.',
    ratings: 4.7,
    sales: 150,
    views: 21500,
    topQuality: false,
    isActive: true,
    pricing: 2800000000,
    image: 'src/assets/images/property-14.jpg',
    location: 'Medan, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 110,
  },
  {
    id: 15,
    title: 'Vila Eksotis di Ubud',
    description:
      'Vila dengan arsitektur Bali yang kental, dikelilingi oleh sawah dan hutan yang asri.',
    ratings: 4.9,
    sales: 85,
    views: 26000,
    topQuality: true,
    isActive: true,
    pricing: 8900000000,
    image: 'src/assets/images/property-15.jpg',
    location: 'Bali, Indonesia',
    type: 'Vila',
    bedrooms: 3,
    bathrooms: 3,
    area: 500,
  },
  {
    id: 16,
    title: 'Apartemen Servis Bintang Lima',
    description:
      'Tinggal dengan kenyamanan hotel di apartemen servis mewah dengan layanan lengkap.',
    ratings: 4.8,
    sales: 190,
    views: 22500,
    topQuality: false,
    isActive: true,
    pricing: 3500000000,
    image: 'src/assets/images/property1.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 90,
  },
  {
    id: 17,
    title: 'Rumah Peternakan Modern',
    description:
      'Properti luas dengan rumah utama modern dan fasilitas peternakan, ideal untuk agrowisata.',
    ratings: 4.7,
    sales: 50,
    views: 15500,
    topQuality: false,
    isActive: true,
    pricing: 9500000000,
    image: 'src/assets/images/property-1.jpg',
    location: 'Malang, Indonesia',
    type: 'Rumah',
    bedrooms: 6,
    bathrooms: 5,
    area: 1500,
  },
  {
    id: 18,
    title: 'Studio Artistik di Kota Tua',
    description:
      'Apartemen studio dengan sentuhan artistik, terletak di kawasan bersejarah Kota Tua.',
    ratings: 4.6,
    sales: 140,
    views: 17500,
    topQuality: false,
    isActive: true,
    pricing: 1300000000,
    image: 'src/assets/images/property-2.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 55,
  },
  {
    id: 19,
    title: 'Rumah Kayu di Pegunungan',
    description:
      'Rumah kayu yang hangat dan nyaman, tempat peristirahatan sempurna di pegunungan.',
    ratings: 4.8,
    sales: 70,
    views: 19500,
    topQuality: true,
    isActive: true,
    pricing: 2800000000,
    image: 'src/assets/images/property-3.jpg',
    location: 'Puncak, Indonesia',
    type: 'Rumah',
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
  },
  {
    id: 20,
    title: 'Apartemen dengan Akses Rooftop Garden',
    description:
      'Apartemen modern yang menawarkan akses eksklusif ke taman di atap gedung.',
    ratings: 4.7,
    sales: 220,
    views: 21000,
    topQuality: false,
    isActive: true,
    pricing: 2600000000,
    image: 'src/assets/images/property-4.jpg',
    location: 'Surabaya, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 1,
    area: 80,
  },
  {
    id: 21,
    title: 'Vila di Atas Tebing',
    description:
      'Vila spektakuler yang dibangun di atas tebing dengan pemandangan laut yang tak terhalang.',
    ratings: 5.0,
    sales: 45,
    views: 28000,
    topQuality: true,
    isActive: true,
    pricing: 25000000000,
    image: 'src/assets/images/property-5.jpg',
    location: 'Bali, Indonesia',
    type: 'Vila',
    bedrooms: 6,
    bathrooms: 7,
    area: 800,
  },
  {
    id: 22,
    title: 'Rumah Cerdas Otomatis',
    description:
      'Rumah masa depan dengan sistem otomatisasi canggih untuk kontrol pencahayaan, suhu, dan keamanan.',
    ratings: 4.9,
    sales: 80,
    views: 23500,
    topQuality: true,
    isActive: true,
    pricing: 7800000000,
    image: 'src/assets/images/property-6.jpg',
    location: 'Tangerang, Indonesia',
    type: 'Rumah',
    bedrooms: 5,
    bathrooms: 5,
    area: 500,
  },
  {
    id: 23,
    title: 'Apartemen Mungil Dekat Kampus',
    description:
      'Apartemen kecil yang terjangkau, berlokasi strategis dekat dengan universitas ternama.',
    ratings: 4.4,
    sales: 450,
    views: 25500,
    topQuality: false,
    isActive: true,
    pricing: 750000000,
    image: 'src/assets/images/property-7.jpg',
    location: 'Bandung, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 28,
  },
  {
    id: 24,
    title: 'Rumah Kolonial Terawat',
    description:
      'Rumah peninggalan era kolonial yang telah direstorasi dengan cermat, menjaga pesona sejarahnya.',
    ratings: 4.8,
    sales: 65,
    views: 20000,
    topQuality: true,
    isActive: true,
    pricing: 6500000000,
    image: 'src/assets/images/property-8.jpg',
    location: 'Semarang, Indonesia',
    type: 'Rumah',
    bedrooms: 7,
    bathrooms: 5,
    area: 900,
  },
  {
    id: 25,
    title: 'Kabin Modern di Hutan Pinus',
    description:
      'Kabin modern di tengah hutan pinus, menawarkan pengalaman glamping yang mewah.',
    ratings: 4.9,
    sales: 100,
    views: 22000,
    topQuality: true,
    isActive: true,
    pricing: 2100000000,
    image: 'src/assets/images/property-9.jpg',
    location: 'Lembang, Indonesia',
    type: 'Kabin',
    bedrooms: 2,
    bathrooms: 1,
    area: 100,
  },
  {
    id: 26,
    title: 'Apartemen dengan Fasilitas Olahraga Lengkap',
    description:
      'Kompleks apartemen dengan gym, kolam renang ukuran olimpiade, dan lapangan tenis.',
    ratings: 4.7,
    sales: 280,
    views: 24000,
    topQuality: false,
    isActive: true,
    pricing: 2900000000,
    image: 'src/assets/images/property-10.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Apartemen',
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
  },
  {
    id: 27,
    title: 'Rumah Terapung Unik',
    description:
      'Pengalaman tinggal yang unik di rumah modern yang terapung di atas danau yang tenang.',
    ratings: 4.8,
    sales: 55,
    views: 18000,
    topQuality: false,
    isActive: true,
    pricing: 3200000000,
    image: 'src/assets/images/property-11.jpg',
    location: 'Cianjur, Indonesia',
    type: 'Rumah',
    bedrooms: 2,
    bathrooms: 2,
    area: 130,
  },
  {
    id: 28,
    title: 'Mansion Megah di Kawasan Elit',
    description:
      'Mansion dengan arsitektur megah, dilengkapi dengan bioskop pribadi dan ballroom.',
    ratings: 5.0,
    sales: 30,
    views: 30000,
    topQuality: true,
    isActive: false,
    pricing: 55000000000,
    image: 'src/assets/images/property-12.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Mansion',
    bedrooms: 10,
    bathrooms: 12,
    area: 2500,
  },
  {
    id: 29,
    title: 'Apartemen Ramah Lingkungan',
    description:
      'Apartemen dengan sertifikasi bangunan hijau, menggunakan panel surya dan sistem daur ulang air.',
    ratings: 4.8,
    sales: 160,
    views: 22500,
    topQuality: true,
    isActive: true,
    pricing: 3300000000,
    image: 'src/assets/images/property-13.jpg',
    location: 'Tangerang, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 85,
  },
  {
    id: 30,
    title: 'Rumah Joglo Autentik',
    description:
      'Rasakan budaya Jawa di rumah Joglo autentik yang telah dimodernisasi fasilitasnya.',
    ratings: 4.7,
    sales: 88,
    views: 19800,
    topQuality: false,
    isActive: true,
    pricing: 4500000000,
    image: 'src/assets/images/property-14.jpg',
    location: 'Solo, Indonesia',
    type: 'Rumah',
    bedrooms: 5,
    bathrooms: 4,
    area: 600,
  },
  {
    id: 31,
    title: 'Vila Modern Tropis',
    description:
      'Vila mewah dengan desain modern tropis, kolam renang pribadi, dan taman yang rimbun.',
    ratings: 4.9,
    sales: 130,
    views: 16000,
    topQuality: true,
    isActive: true,
    pricing: 8000000000,
    image: 'src/assets/images/property-1.jpg',
    location: 'Canggu, Bali',
    type: 'Vila',
    bedrooms: 4,
    bathrooms: 4,
    area: 550,
  },
  {
    id: 32,
    title: 'Apartemen Urban Chic',
    description:
      'Apartemen stylish di pusat kota, cocok untuk gaya hidup urban yang dinamis.',
    ratings: 4.6,
    sales: 280,
    views: 24000,
    topQuality: false,
    isActive: true,
    pricing: 2800000000,
    image: 'src/assets/images/property-2.jpg',
    location: 'Jakarta Selatan, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 85,
  },
  {
    id: 33,
    title: 'Rumah Kebun Asri',
    description:
      'Rumah dengan kebun buah dan sayur organik, oase hijau di tengah kota.',
    ratings: 4.8,
    sales: 110,
    views: 19000,
    topQuality: true,
    isActive: true,
    pricing: 4500000000,
    image: 'src/assets/images/property-3.jpg',
    location: 'Sentul, Indonesia',
    type: 'Rumah',
    bedrooms: 3,
    bathrooms: 3,
    area: 400,
  },
  {
    id: 34,
    title: 'Penthouse dengan Jacuzzi Pribadi',
    description:
      'Nikmati kemewahan dengan jacuzzi pribadi di balkon penthouse Anda.',
    ratings: 4.9,
    sales: 70,
    views: 26000,
    topQuality: true,
    isActive: true,
    pricing: 18000000000,
    image: 'src/assets/images/property-4.jpg',
    location: 'Jakarta Pusat, Indonesia',
    type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 5,
    area: 420,
  },
  {
    id: 35,
    title: 'Rumah Cluster Baru',
    description:
      'Rumah baru di cluster eksklusif dengan keamanan 24 jam dan one-gate system.',
    ratings: 4.5,
    sales: 200,
    views: 21000,
    topQuality: false,
    isActive: true,
    pricing: 2900000000,
    image: 'src/assets/images/property-5.jpg',
    location: 'Serpong, Indonesia',
    type: 'Rumah',
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
  },
  {
    id: 36,
    title: 'Apartemen Mezzanine Unik',
    description:
      'Apartemen dengan lantai mezzanine untuk ruang kerja atau kamar tidur tambahan.',
    ratings: 4.7,
    sales: 125,
    views: 17500,
    topQuality: false,
    isActive: true,
    pricing: 1900000000,
    image: 'src/assets/images/property-6.jpg',
    location: 'Bandung, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 95,
  },
  {
    id: 37,
    title: 'Penginapan Tepi Sungai',
    description:
      'Properti menawan di tepi sungai, cocok untuk memancing dan bersantai.',
    ratings: 4.8,
    sales: 90,
    views: 22000,
    topQuality: true,
    isActive: true,
    pricing: 5800000000,
    image: 'src/assets/images/property-7.jpg',
    location: 'Bogor, Indonesia',
    type: 'Resor',
    bedrooms: 8,
    bathrooms: 9,
    area: 1000,
  },
  {
    id: 38,
    title: 'Townhouse dengan Kolam Renang Komunal',
    description:
      'Townhouse modern dengan akses ke kolam renang dan gym eksklusif untuk penghuni.',
    ratings: 4.6,
    sales: 230,
    views: 22500,
    topQuality: false,
    isActive: true,
    pricing: 2400000000,
    image: 'src/assets/images/property-8.jpg',
    location: 'Cibubur, Indonesia',
    type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 3,
    area: 170,
  },
  {
    id: 39,
    title: 'Bungalow Pantai Pribadi',
    description:
      'Bungalow eksklusif dengan akses langsung ke pantai pribadi yang sepi.',
    ratings: 4.9,
    sales: 95,
    views: 18000,
    topQuality: true,
    isActive: true,
    pricing: 4000000000,
    image: 'src/assets/images/property-9.jpg',
    location: 'Gili Trawangan, Lombok',
    type: 'Bungalow',
    bedrooms: 2,
    bathrooms: 2,
    area: 280,
  },
  {
    id: 40,
    title: 'Apartemen Studio Fully Furnished',
    description:
      'Apartemen studio siap huni dengan perabotan lengkap dan desain interior modern.',
    ratings: 4.5,
    sales: 320,
    views: 25000,
    topQuality: false,
    isActive: true,
    pricing: 1100000000,
    image: 'src/assets/images/property-10.jpg',
    location: 'Bekasi, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 40,
  },
  {
    id: 41,
    title: 'Rumah Gaya Skandinavia',
    description:
      'Rumah dengan desain interior Skandinavia yang cerah, bersih, dan fungsional.',
    ratings: 4.8,
    sales: 115,
    views: 20500,
    topQuality: true,
    isActive: true,
    pricing: 5000000000,
    image: 'src/assets/images/property-11.jpg',
    location: 'Bandung, Indonesia',
    type: 'Rumah',
    bedrooms: 4,
    bathrooms: 3,
    area: 420,
  },
  {
    id: 42,
    title: 'Kondominium di Lapangan Golf',
    description:
      'Kondominium mewah dengan pemandangan langsung ke lapangan golf hijau yang luas.',
    ratings: 4.9,
    sales: 85,
    views: 25500,
    topQuality: true,
    isActive: true,
    pricing: 13500000000,
    image: 'src/assets/images/property-12.jpg',
    location: 'Bogor, Indonesia',
    type: 'Kondominium',
    bedrooms: 3,
    bathrooms: 4,
    area: 320,
  },
  {
    id: 43,
    title: 'Rumah Urban Garden',
    description:
      'Rumah di perkotaan dengan taman vertikal dan rooftop garden yang inovatif.',
    ratings: 4.7,
    sales: 140,
    views: 19500,
    topQuality: false,
    isActive: true,
    pricing: 4100000000,
    image: 'src/assets/images/property-13.jpg',
    location: 'Surabaya, Indonesia',
    type: 'Rumah',
    bedrooms: 4,
    bathrooms: 3,
    area: 300,
  },
  {
    id: 44,
    title: 'Apartemen Loteng Terbuka',
    description:
      'Apartemen konsep loteng dengan langit-langit tinggi dan ruang terbuka yang luas.',
    ratings: 4.7,
    sales: 160,
    views: 23000,
    topQuality: false,
    isActive: true,
    pricing: 3000000000,
    image: 'src/assets/images/property-14.jpg',
    location: 'Jakarta Barat, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 130,
  },
  {
    id: 45,
    title: 'Vila Sawah di Tegallalang',
    description:
      'Vila menawan yang menghadap langsung ke terasering sawah ikonik di Tegallalang.',
    ratings: 4.9,
    sales: 90,
    views: 27500,
    topQuality: true,
    isActive: true,
    pricing: 9200000000,
    image: 'src/assets/images/property-15.jpg',
    location: 'Bali, Indonesia',
    type: 'Vila',
    bedrooms: 3,
    bathrooms: 4,
    area: 520,
  },
  {
    id: 46,
    title: 'Apartemen Transit-Oriented',
    description:
      'Apartemen yang terintegrasi langsung dengan stasiun MRT dan pusat transportasi.',
    ratings: 4.8,
    sales: 210,
    views: 24500,
    topQuality: false,
    isActive: true,
    pricing: 3800000000,
    image: 'src/assets/images/property1.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 95,
  },
  {
    id: 47,
    title: 'Rumah Kebun Anggur',
    description:
      'Properti unik dengan kebun anggur pribadi dan fasilitas pembuatan wine.',
    ratings: 4.7,
    sales: 60,
    views: 16500,
    topQuality: false,
    isActive: true,
    pricing: 10500000000,
    image: 'src/assets/images/property-1.jpg',
    location: 'Bali Utara, Indonesia',
    type: 'Rumah',
    bedrooms: 5,
    bathrooms: 6,
    area: 1800,
  },
  {
    id: 48,
    title: 'Studio Compact di CBD',
    description:
      'Apartemen studio fungsional di Central Business District, ideal untuk pebisnis.',
    ratings: 4.6,
    sales: 155,
    views: 18500,
    topQuality: false,
    isActive: true,
    pricing: 1500000000,
    image: 'src/assets/images/property-2.jpg',
    location: 'Jakarta, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 45,
  },
  {
    id: 49,
    title: 'Rumah Bambu Ramah Lingkungan',
    description:
      'Rumah unik yang dibangun hampir seluruhnya dari bambu, menyatu dengan alam.',
    ratings: 4.8,
    sales: 75,
    views: 21500,
    topQuality: true,
    isActive: true,
    pricing: 3200000000,
    image: 'src/assets/images/property-3.jpg',
    location: 'Ubud, Bali',
    type: 'Rumah',
    bedrooms: 3,
    bathrooms: 2,
    area: 220,
  },
  {
    id: 50,
    title: 'Apartemen dengan Pemandangan Monas',
    description:
      'Apartemen di gedung tinggi dengan pemandangan langsung ke Monumen Nasional.',
    ratings: 4.7,
    sales: 240,
    views: 23500,
    topQuality: false,
    isActive: true,
    pricing: 2750000000,
    image: 'src/assets/images/property-4.jpg',
    location: 'Jakarta Pusat, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 1,
    area: 82,
  },
  {
    id: 51,
    title: 'Vila Mediterania Putih',
    description:
      'Vila dengan arsitektur Mediterania yang didominasi warna putih, bersih dan elegan.',
    ratings: 4.9,
    sales: 55,
    views: 29000,
    topQuality: true,
    isActive: true,
    pricing: 19000000000,
    image: 'src/assets/images/property-5.jpg',
    location: 'Uluwatu, Bali',
    type: 'Vila',
    bedrooms: 5,
    bathrooms: 6,
    area: 750,
  },
  {
    id: 52,
    title: 'Rumah Cerdas Minimalis',
    description:
      'Rumah minimalis yang dilengkapi dengan teknologi smart home untuk kenyamanan maksimal.',
    ratings: 4.9,
    sales: 95,
    views: 24500,
    topQuality: true,
    isActive: true,
    pricing: 8200000000,
    image: 'src/assets/images/property-6.jpg',
    location: 'BSD City, Indonesia',
    type: 'Rumah',
    bedrooms: 4,
    bathrooms: 4,
    area: 480,
  },
  {
    id: 53,
    title: 'Apartemen Mahasiswa Terjangkau',
    description:
      'Pilihan tepat untuk mahasiswa, apartemen terjangkau dengan lokasi dekat berbagai kampus.',
    ratings: 4.4,
    sales: 500,
    views: 27000,
    topQuality: false,
    isActive: true,
    pricing: 800000000,
    image: 'src/assets/images/property-7.jpg',
    location: 'Jatinangor, Indonesia',
    type: 'Apartemen',
    bedrooms: 1,
    bathrooms: 1,
    area: 25,
  },
  {
    id: 54,
    title: 'Rumah Heritage di Pusat Kota',
    description:
      'Bangunan cagar budaya yang dijadikan hunian, perpaduan pesona klasik dan kenyamanan modern.',
    ratings: 4.8,
    sales: 70,
    views: 21000,
    topQuality: true,
    isActive: true,
    pricing: 7200000000,
    image: 'src/assets/images/property-8.jpg',
    location: 'Yogyakarta, Indonesia',
    type: 'Rumah',
    bedrooms: 6,
    bathrooms: 4,
    area: 850,
  },
  {
    id: 55,
    title: 'Kabin Gunung dengan Pemandian Air Panas',
    description:
      'Kabin nyaman di gunung dengan akses ke pemandian air panas alami.',
    ratings: 4.9,
    sales: 110,
    views: 23000,
    topQuality: true,
    isActive: true,
    pricing: 2500000000,
    image: 'src/assets/images/property-9.jpg',
    location: 'Ciwidey, Indonesia',
    type: 'Kabin',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
  },
  {
    id: 56,
    title: 'Apartemen dengan Co-working Space',
    description:
      'Kompleks apartemen modern yang dilengkapi dengan co-working space untuk penghuninya.',
    ratings: 4.7,
    sales: 300,
    views: 25500,
    topQuality: false,
    isActive: true,
    pricing: 3100000000,
    image: 'src/assets/images/property-10.jpg',
    location: 'Jakarta Selatan, Indonesia',
    type: 'Apartemen',
    bedrooms: 3,
    bathrooms: 2,
    area: 115,
  },
  {
    id: 57,
    title: 'Rumah Kontainer Inovatif',
    description:
      'Hunian inovatif dan ramah lingkungan yang terbuat dari kontainer bekas.',
    ratings: 4.6,
    sales: 80,
    views: 19000,
    topQuality: false,
    isActive: true,
    pricing: 1500000000,
    image: 'src/assets/images/property-11.jpg',
    location: 'Bekasi, Indonesia',
    type: 'Rumah',
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
  },
  {
    id: 58,
    title: 'Mansion Klasik Eropa',
    description:
      'Mansion mewah dengan detail arsitektur klasik Eropa, taman formal, dan air mancur.',
    ratings: 5.0,
    sales: 35,
    views: 32000,
    topQuality: true,
    isActive: true,
    pricing: 60000000000,
    image: 'src/assets/images/property-12.jpg',
    location: 'Pondok Indah, Jakarta',
    type: 'Mansion',
    bedrooms: 8,
    bathrooms: 10,
    area: 2200,
  },
  {
    id: 59,
    title: 'Apartemen Hijau dengan Balkon Luas',
    description:
      'Setiap unit apartemen memiliki balkon luas untuk berkebun dan bersantai.',
    ratings: 4.8,
    sales: 180,
    views: 23500,
    topQuality: true,
    isActive: true,
    pricing: 3600000000,
    image: 'src/assets/images/property-13.jpg',
    location: 'Alam Sutera, Indonesia',
    type: 'Apartemen',
    bedrooms: 2,
    bathrooms: 2,
    area: 90,
  },
  {
    id: 60,
    title: 'Rumah Adat Toraja Modern',
    description:
      'Rumah dengan desain terinspirasi dari Tongkonan, rumah adat Toraja, dengan fasilitas modern.',
    ratings: 4.7,
    sales: 92,
    views: 20500,
    topQuality: false,
    isActive: true,
    pricing: 4800000000,
    image: 'src/assets/images/property-14.jpg',
    location: 'Makassar, Indonesia',
    type: 'Rumah',
    bedrooms: 5,
    bathrooms: 4,
    area: 550,
  },
];